plugins {
    id 'java'
    id 'org.sonarqube' version '5.1.0.4882'
}

allprojects {
    group = 'com.jobportal'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    if (project.path != ':services') {
        apply plugin: 'java'

        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}

sonar {
    properties {
        property 'sonar.projectKey', 'jobsportalgradle'
        property 'sonar.projectName', 'jobsportalgradle'
        property 'sonar.host.url', System.getenv('SONAR_HOST_URL') ?: 'http://localhost:9000'
    }
}

