pluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }

rootProject.name = 'jobs-portal-backend'

include(
    'services:auth-service',
    'services:job-service',
    'services:admin-service',
    'services:application-service',
    'services:notification-service',
    'services:discovery-server',
    'services:config-server',
    'services:api-gateway'
)
