server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:/Users/smitm/Downloads/jobsportalgradle/infrastructure/promtail/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-services
    static_configs:
      - targets: [localhost]
        labels:
          job: local-services
          host: windows
          __path__: C:/Users/smitm/Downloads/jobsportalgradle/logs/*.log

